[general]
geofence_path = "config/geofences"
init = true


[stopwatcher_db]
username = ""
password = ""
host = "0.0.0.0"
port = 3306
database = "stopwatcher"


[tileserver]
enable = true
url = "https://tiles.domain.com"

[tileserver.visual]
style = "osm-bright"
cells = ["portal", "lightship_poi"]
nearby_forts = ["pokestop", "gym", "portal", "lightship_poi"]
zoom = 17.5
size = "800x500"  # width x height
scale = 1


[data_input]

[data_input.webhooks]
host = "127.0.0.1"
port = 9292
username = "stopwatcher"
password = "strongpass"

[data_input.database_config]
query_every = 300  # seconds
difference_threshold = 20  # when a missing X forts are detected, they're copied directly without processing

[data_input.database.1]
db_schema = "rdm"  # rdm or mad
username = ""
password = ""
host = "0.0.0.0"
port = 3306
database = "rdmrb"


[areas]

[areas.example]

[areas.example.discord.1]
webhooks = ["https://discord.com/webhooks/1"]
types = ["pokestop", "gym"]
send = ["new", "new_details", "removed", "conversion", "edit_name", "edit_description", "edit_location", "edit_cover"]

[areas.example.discord.this_value_doesnt_matter]
webhooks = ["https://discord.com/webhooks/2"]
types = ["portal", "lighship_poi"]
send = ["new", "new_details", "removed", "conversion", "edit_name", "edit_description", "edit_location", "edit_cover"]

